### ISSUE TITLE
ClonableSubtitleFile not publicly exported

### ISSUE THREAD

**Issue by walfie** [kaegi/subparse#3]
`subparse::parse_str` has `ClonableSubtitleFile` as part of its return type, but that type isn't exported in the crate's public interface.

Basically I am trying to define an internal helper function in my code that uses `parse_str` to return a `Box<SubtitleFile>`, but I am having issues since `ClonableSubtitleFile` is private and I can't seem to cast the types properly.

**Comment by walfie** [comment]
Here is the workaround I am using locally for now:
https://github.com/kaegi/subparse/compare/master...walfie:subtitle-variant

rather than expose `ClonableSubtitleFile` as a public export (since it seems to be an internal workaround for clonable trait objects) I just converted it to an `enum` with all the variants, and wrapped it in a struct which implements the `SubtitleFile` trait by enum matching.

It does have some size implications (the enum will take the size of the largest variant, since it's no longer boxed) and is a breaking change since it now requires importing `SubtitleFile` to get the trait in scope, so I'm hesitant to open it as a PR. But in case anyone was interested, there it is.

**Comment by kaegi** [comment]
Thanks! Yes, the `ClonableSubtitleFile` is a workaround for cloneable trait objects. Exposing it should in principle not be a problem (except for a new 0.x.x version).
It might be possible to create a better solution using `impl Trait` and without boxing, but that will take some time to getting around to implement it.

If that doesn't work, your version seems to be a better fit for this library. I wanted to keep things as generic/abstract/extensible as possible (using just traits), but if this creates problems, manually enumerating all types is probably better.

**Comment by walfie** [comment]
Thanks, that makes sense. I've opened a PR at #4 for the simple approach of just making it public, for now.
